### ISSUE TITLE
Letter case not preserved

### ISSUE THREAD

**Issue by geneopsramp** [opsramp/openapi-specs#16]
[IGNORE: duplicated as issue @216 in the main repository]

In a random look at two files, camelcase is not preserved in the examples in the generated HTML:

/api/v2/alerts/tenants-tenantid-alerts-alertid-incidents-incidentid-attach.yaml
/api/v2/alerts/tenants-tenantid-alertstatushistory-alertid.yaml

YAML:
```
          examples:
            example-1:
              value:
                alertId: 2156
                createdBy: system
                createdTime: '2019-04-02T14:27:55+0000'
                acknowledgedBy: superadmin
                acknowledgedTime: '2019-04-02T14:33:18+0000'
                suppressedBy: superadmin
                suppressedTime: '2019-04-02T14:33:59+0000'

```
HTML:
```
{
  "acknowledgedby": "superadmin",
  "acknowledgedtime": "2019-04-02T14:33:18+0000",
  "alertid": 2156,
  "createdby": "system",
  "createdtime": "2019-04-02T14:27:55+0000",
  "suppressedby": "superadmin",
  "suppressedtime": "2019-04-02T14:33:59+0000"
}
```
