### ISSUE TITLE
Not recognizing example description (summary:)

### ISSUE THREAD

**Issue by geneopsramp** [opsramp/openapi-specs#22]
The `summary` field in `example` is not rendered:

```
          examples:
            example-1:
              value:
              summary: Request with smartFilters response
                API_GATEWAY: API Gateways
                AWS_APP_MESH: App Mesh
                AWS_APP_STREAM: App Stream
                AWS_APPSYNC: App Sync API
```
