### ISSUE TITLE
Incorrect syntax being used for response examples

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#24]
This applies to all examples, but the problem seems to be most prevalent for response examples. Please see https://swagger.io/docs/specification/adding-examples/ for reference.

When using the `examples` parameter, the example must be provided as a `value`. For instance:

```
# Incorrect
examples:
  example-1:
    Success: Service Squid Proxy started successfully.

# Correct
examples:
  example-1:
    value:
      Success: Service Squid Proxy started successfully.
```

A recent request to display example summaries has caused the theme to break on this error, as some of the examples are returning as strings, while others are returning as maps, as they should.

Please review all response examples and ensure that the correct syntax appears.

**Comment by geneopsramp** [comment]
For this file: .../docs/openapi-specs/v2/tenancy-access-controls/tenants-tenantid-resourcetypes-google.yaml
I think this is valid syntax:
          examples:
            example-1:
              summary: Request with smartFilters response
              value:
I'd expect summary to generate a description but no description was rendered.
Slightly different than the problem stated in this issue, which is still valid and will be fixed.

**Comment by mwaterous** [comment]
That is valid, yes. The theme in its present state isn't rendering those summaries, as it cannott, until all examples are using the proper syntax as outlined above. The issue is that Hugo doesn't have a way to differentiate between types:

```
examples:
  example-1:
    Success: Service Squid Proxy started successfully.
```

The above returns a string, while the below returns an array/map:

```
examples:
  example-1:
    value:
      Success: Service Squid Proxy started successfully.
```

Due to the limitations of Hugo templates, I can't say `if string do this else if array do that` and have to treat them all as strings for the time being (which precludes the summary from working). It's a pretty big weakness I've run into once or twice while building the theme.

I can provide some assistance updating all the OpenAPI yaml's if you'd like. Once that's been cleared up I can update the theme so that it is capable of displaying a summary for those that have it, but as you mentioned it will be optional since many examples won't need to make use of it.
