### ISSUE TITLE
repeatType in automation only has a single possible value

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#51]
```yaml
        repeatType:
          type: string
          description: Run the job constantly on specific days.
          enum:
            - days
```

Found here:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-automation.v2.yaml#L1887

Only has a single possible value, "days". Properties with only a single accepted value seem redundant so I wanted to confirm if this was the correct defintion.
