### ISSUE TITLE
incident description includes empty array

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#57]
The reference for `incident` in tickets has a property, `alertIds` which is defined as an array but contains to items:

https://github.com/opsramp/openapi-specs/blob/a5cb1095590f34d70add7dcb0bb449235d0253aa/v2/opsramp-tickets.v2.yaml#L16876

The full three lines looks like:
```yaml
        alertIds:
          type: array
          items: {}
```

If this is an array of objects, it should look something like this I believe:
```yaml
        alertIds:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: a string included in this object
```
