### ISSUE TITLE
Property needs description

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#62]
Docs: https://opsramp-api-develop.markwaterous.dev/agents-gateways/tenants-tenantid-agents-agentversion-resourcescountbyagentversion

Spec:
https://github.com/opsramp/openapi-specs/blob/baac35e64d71f7a91900d765958cbd501f0a1011/v2/opsramp-agents-gateways.v2.yaml#L324

Endpoint returns one field from a get request, `version` with an integer. I'm assuming that integer is the number of installed agent resources for that agent version?

Optimally the returned response from such an endpoint could be more intuitive:
```json
{
  "version": "1.0",
  "count": 4
}
```

Where version reflects the same version sent in the request, used for comparison, and count is the number of installed agent resources. If this is a change that can't be made to the API itself, we should add a description to clarify:

```yaml
                properties:
                  version:
                    type: integer
                    description: The number of currently installed agent resources for the requested version
```
